// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgDJfQQgvEbKfv3JJDx01SrLdeI68Y0xw',
    appId: '1:845063938504:web:33587054ad981629ab20fd',
    messagingSenderId: '845063938504',
    projectId: 'gymapp-eb3f5',
    authDomain: 'gymapp-eb3f5.firebaseapp.com',
    storageBucket: 'gymapp-eb3f5.firebasestorage.app',
    measurementId: 'G-CKY8Z8HNQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQFQlQrFhIa2ffnIXFAZ7zeXGiExcXlIA',
    appId: '1:845063938504:android:6e96d4db192d151dab20fd',
    messagingSenderId: '845063938504',
    projectId: 'gymapp-eb3f5',
    storageBucket: 'gymapp-eb3f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BFyGyuAXgWQA00_YpJV-Ph2YftphN6Y',
    appId: '1:845063938504:ios:2c07d77e1d1f57e1ab20fd',
    messagingSenderId: '845063938504',
    projectId: 'gymapp-eb3f5',
    storageBucket: 'gymapp-eb3f5.firebasestorage.app',
    iosBundleId: 'com.codeforany.healthoGym',
  );
}
